### ISSUE TITLE
Change pyTMD version requirement

### ISSUE THREAD

**Issue by mpaget** [auspatious/coastlines#3]
Hi @alexgleith,

`setup.py` pins `pyTMD==2.1.4`. Can this be changed to ">=", please?

https://github.com/GeoscienceAustralia/eo-tides also pins `pyTMD` (presently 2.1.8 but earlier versions require at least 2.1.6). These restrictions mean that the `coastlines` and `eo-tides` packages are incompatible in the same python environment.

**Comment by alexgleith** [comment]
Sure thing @mpaget! Want to shoot a PR?

**Comment by alexgleith** [comment]
Closed with #5
